name: ChestFix
version: 0.4
main: com.gmail.igotburnt.ChestFix.ChestFix
author: Netherfoam

description: Prevents chests being accessed through walls. Includes furnaces etc.
website: http://maxgamer.org
softdepend: [HawkEye]
